[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
nom = "7.1.3"
once_cell = "1.20.2"
paste = "1.0.15"
regex = "1.11.1"
smallvec = "1.13.2"
