[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
once_cell = "1.20.2"
paste = "1.0.15"
regex = "1.11.1"
